---

- hosts: all
  become: true
  tasks:

  - name: install apache2 on all server
    apt:
      name: apache2
      state: absent

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
  
  - name: update repository index
    apt:
      update_cache: yes 
